### ISSUE TITLE
Error when moving Asset to different folder

### ISSUE THREAD

**Issue by Thane5** [LifeandStyleMedia/UniversalSave#2]
I moved the "Universal Save" folder into my Tools folder, and got this error that prevents me from entering playmode:
```
Microsoft (R) Visual C# Compiler version 3.5.0-dev-20359-01 (8da8ba0c)
Copyright (C) Microsoft Corporation. All rights reserved.

error CS0006: Metadata file 'Assets/LifeandStyleMedia/Bolt/UniversalSave/Odin Serializer/EditorOnly/Lasm.Bolt.UniversalSaver.OdinSerializer.dll' could not be found
```

**Comment by MasterSubby** [comment]
Sorry, didn't get any email about this. I've seen that error, in other places, even without Bolt. I don't think it directly relates to Universal Save, but something to do with the moving of dlls that are already hooked in. Their is no assembly definitions, or special code. The dll is just a namespace modification to Odin Serializer to have our own version. I'm not sure that it is something I can fix or not. I'll need to look up more information to make sure I'm right or not on this.

Has this ever happened with other dlls moved that aren't this?  Once you restart, this error would be resolved, I assume?

**Comment by Thane5** [comment]
When i created this issue, restarting wouldn't help. But i just tried it again on the same project (with a new uinity version) and the error is gone.
